### ISSUE TITLE
无法添加依赖模块

### ISSUE THREAD

**Issue by CxwIT** [netsuite-upload-org/netsuite-upload#36] opened 2019-10-22 04:02 UTC
Issue Type: <b>Feature Request</b>

当我使用 ctrl+shift+p命令  输入
add netsuite dependency 和 add custom dependency 命令时，它加入的依赖只会在function里面，不会放置到  define里面
![image](https://user-images.githubusercontent.com/38432314/67258555-d7554300-f4c3-11e9-8ebb-cbbb29232043.png)

Extension version: 1.2.2
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

**Comment by silverl** [comment] 2019-10-24 21:14
This is a duplicate of #31

**Closed by silverl** 2019-10-24 21:14 UTC
